/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package project.boundary;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import java.awt.Graphics2D;
import java.awt.FontMetrics;
import java.awt.BasicStroke;

/**
 *
 * @author lucas
 */
public class PlayerIcon extends javax.swing.JPanel {
    private Image image;
    private String playerName;

    /**
     * Creates new form PlayerIcon
     */
    public PlayerIcon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
        Graphics2D g2d = (Graphics2D) g;
        
        int width = getWidth();
        int height = getHeight();
        
        double imgProportion = 0.75;
        double nameProportion = 1 - imgProportion;
        
        // draw frame
        g2d.setColor(Color.WHITE);
        g2d.fillRect(0, 0, width, height);
        
        g2d.setColor(Color.BLACK);
        g2d.setStroke(new BasicStroke(4));
        g2d.drawRect(2, 2, width-4,(int) (height*imgProportion));
        
        int padding = 5;
        
        if (image != null) {
            int imgHeight = (int) (height*imgProportion);
            g2d.drawImage(image, padding, padding, width-2*padding, imgHeight-2*padding, this);
        }
        
        if (playerName != null) {
            int fontSize = (int) (height * nameProportion);
            g2d.setFont(new Font("Arial", Font.BOLD, fontSize));
            g2d.setColor(Color.BLACK);

            FontMetrics fm = g2d.getFontMetrics();
            int texteWidth = fm.stringWidth(playerName);

            int x = (width - texteWidth) / 2;
            int y = (int) (height - (height*nameProportion)/fontSize);

            g2d.drawString(playerName, x, y);
        }
        
    }

    private void setImage(String name) {
        String path = "/images/"+name+".png";
        ImageIcon icon = new ImageIcon(getClass().getResource(path));
        image = icon.getImage();
        repaint();
    }

    public void setPlayerName(String playerName) {
        this.playerName = playerName;
        setImage(playerName);
        repaint();
    }
    
    
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    
}
