/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package project.boundary;

import java.awt.Dimension;
import java.awt.Graphics;

/**
 *
 * @author lucas
 */
public class PlayerComponent extends javax.swing.JPanel {

    /**
     * Creates new form PlayerComponent
     */
    public PlayerComponent() {
        initComponents();
        Dimension size = new Dimension(255, 100);
        this.setPreferredSize(size);
        this.setSize(size);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playerIcon1 = new project.boundary.PlayerIcon();
        heart1 = new project.boundary.Heart();
        heart2 = new project.boundary.Heart();
        heart3 = new project.boundary.Heart();
        heart4 = new project.boundary.Heart();
        heart5 = new project.boundary.Heart();

        javax.swing.GroupLayout playerIcon1Layout = new javax.swing.GroupLayout(playerIcon1);
        playerIcon1.setLayout(playerIcon1Layout);
        playerIcon1Layout.setHorizontalGroup(
                playerIcon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 150, Short.MAX_VALUE)
        );
        playerIcon1Layout.setVerticalGroup(
                playerIcon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout heart1Layout = new javax.swing.GroupLayout(heart1);
        heart1.setLayout(heart1Layout);
        heart1Layout.setHorizontalGroup(
                heart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 69, Short.MAX_VALUE)
        );
        heart1Layout.setVerticalGroup(
                heart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 93, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout heart2Layout = new javax.swing.GroupLayout(heart2);
        heart2.setLayout(heart2Layout);
        heart2Layout.setHorizontalGroup(
                heart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 40, Short.MAX_VALUE)
        );
        heart2Layout.setVerticalGroup(
                heart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 65, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout heart3Layout = new javax.swing.GroupLayout(heart3);
        heart3.setLayout(heart3Layout);
        heart3Layout.setHorizontalGroup(
                heart3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 40, Short.MAX_VALUE)
        );
        heart3Layout.setVerticalGroup(
                heart3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 65, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout heart4Layout = new javax.swing.GroupLayout(heart4);
        heart4.setLayout(heart4Layout);
        heart4Layout.setHorizontalGroup(
                heart4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 40, Short.MAX_VALUE)
        );
        heart4Layout.setVerticalGroup(
                heart4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 65, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout heart5Layout = new javax.swing.GroupLayout(heart5);
        heart5.setLayout(heart5Layout);
        heart5Layout.setHorizontalGroup(
                heart5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 40, Short.MAX_VALUE)
        );
        heart5Layout.setVerticalGroup(
                heart5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 65, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(playerIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(heart1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(heart2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(heart3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(heart4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(heart5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 342, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(playerIcon1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(heart3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(heart4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(heart5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(heart2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(heart1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(101, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private project.boundary.Heart heart1;
    private project.boundary.Heart heart2;
    private project.boundary.Heart heart3;
    private project.boundary.Heart heart4;
    private project.boundary.Heart heart5;
    private project.boundary.PlayerIcon playerIcon1;
    // End of variables declaration//GEN-END:variables


    public void setPlayerName(String name){
        playerIcon1.setPlayerName(name);
        repaint();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody


        int w = getWidth();
        int h = getHeight();


        playerIcon1.setBounds(0, 0, h*3/4, h);
        playerIcon1.repaint();

        int heartSize = h/3;
        int gap = w/75;

        int curWidthPos = h*3/4 + gap;
        Heart[] hearts = {heart1,heart2,heart3,heart4,heart5};

        for (Heart heart : hearts) {
            curWidthPos += gap;
            heart.setBounds(curWidthPos, h/20, heartSize, heartSize);
            heart.repaint();
            curWidthPos += heartSize;
        }
    }

    public void setNbHeart(int nbHeart) {
        Heart[] hearts = {heart1,heart2,heart3,heart4,heart5};
        for (int i = 0; i < nbHeart; i++) {
            hearts[i].setLiveHeart(true);
        }
        for (int i = nbHeart; i < 5; i++) {
            hearts[i].setLiveHeart(false);
        }
        repaint();
    }
}