/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project.boundary;

import javax.swing.TransferHandler;
import java.awt.BorderLayout;
import java.awt.FlowLayout;

/**
 *
 * @author cbel
 */
public class TestBomb extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TestBomb.class.getName());

    /**
     * Creates new form testBomb
     */
    public TestBomb() {
        initComponents();
        setupDragDrop();
    }

    private void setupDragDrop() {
        TransfertHandler handler = new TransfertHandler();
        bombe1.setTransferHandler(handler);
        bombe1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            @Override
            public void mouseDragged(java.awt.event.MouseEvent e) {
                TransferHandler th = bombe1.getTransferHandler();
                th.exportAsDrag(bombe1, e, TransferHandler.MOVE);
            }
        });

        // 8 JPanel numérotés (cases 1 à 8)
        javax.swing.JPanel casesPanel = new javax.swing.JPanel(new FlowLayout(FlowLayout.LEFT, 6, 6));
        casesPanel.setBackground(new java.awt.Color(230, 230, 230));
        casesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(
                "Cases cibles  — glisse la bombe sur une case"));

        for (int i = 0; i < 8; i++) {
            javax.swing.JPanel casePanel = new javax.swing.JPanel();
            casePanel.setPreferredSize(new java.awt.Dimension(75, 55));
            casePanel.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.BLACK));
            casePanel.add(new javax.swing.JLabel("Case " + (i + 1)));
            casePanel.setTransferHandler(handler); // zone de drop
            casesPanel.add(casePanel);
        }

        // Restructure le content pane pour afficher bombe + cases
        getContentPane().setLayout(new BorderLayout(10, 10));
        getContentPane().removeAll();
        getContentPane().add(bombe1, BorderLayout.NORTH);
        getContentPane().add(casesPanel, BorderLayout.CENTER);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bombe1 = new project.boundary.BombComponent();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(bombe1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(bombe1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TestBomb().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private project.boundary.BombComponent bombe1;
    // End of variables declaration//GEN-END:variables
}
