/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project.boundary;

/**
 *
 * @author lucas
 */
public class TestPlayerComponent extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TestPlayerComponent.class.getName());

    /**
     * Creates new form TestPlayerComponent
     */
    public TestPlayerComponent() {
        initComponents();
        playerComponent1.setPlayerName("bob");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playerComponent1 = new project.boundary.PlayerComponent();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        playerComponent1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                playerPressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                playerReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(playerComponent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(playerComponent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int releaseCouter = 0;
    int pressCounter = 0;
    
    private void playerPressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playerPressed
        pressCounter++;
        playerComponent1.setNbHeart(pressCounter%6);
        System.out.println("mouse pressed : "+pressCounter);
    }//GEN-LAST:event_playerPressed

    private void playerReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playerReleased
        releaseCouter++;
        if (releaseCouter%3==0) {
            playerComponent1.setPlayerName("bob");
        }else if (releaseCouter%5==0) {
            playerComponent1.setPlayerName("plankton");
        }
        System.out.println("mouse released : "+releaseCouter);
        
    }//GEN-LAST:event_playerReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TestPlayerComponent().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private project.boundary.PlayerComponent playerComponent1;
    // End of variables declaration//GEN-END:variables
}
