/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project.boundary;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JPanel;

/**
 *
 * @author alban
 */
public class testGame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(testGame.class.getName());
    
    private Pawn pionJoueur1;
    private Pawn pionJoueur2;
    private int posJ1 = 0;
    private int posJ2 = 0;
    private int viesJ1 = 5;
    private int viesJ2 = 5;
    private boolean isRolling = false;

    /**
     * Creates new form testGame
     */
    public testGame() {
        initComponents();
        initCustomComponents();
        lancerTestComplet();
    }
    
    private void lancerTestComplet() {
        List<JComponent> casesVisuelles = new ArrayList<>();
        for (int i = 0; i < 30; i++) {
            casesVisuelles.add(new CaseComponent());
        }
        board1.initBoard(casesVisuelles);
        
        player1Comp.setPlayerName("Bob");
        player1Comp.setNbHeart(5);

        player2Comp.setPlayerName("Plankton");
        player2Comp.setNbHeart(5);
        
        pionJoueur1 = new Pawn();
        pionJoueur1.setSize(50, 50);
        pionJoueur1.setImagePath("/images/bob.png");

        pionJoueur2 = new Pawn();
        pionJoueur2.setSize(50, 50);
        pionJoueur2.setImagePath("/images/plankton.png");

        board1.movePlayer(pionJoueur1, posJ1, true);
        board1.movePlayer(pionJoueur2, posJ2, false);
        
        this.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_LEFT) {
                    if (posJ1 < 29) {
                        posJ1++;
                        board1.movePlayer(pionJoueur1, posJ1, true);
                    }
                } else if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_RIGHT) {
                    if (posJ2 < 29) {
                        posJ2++;
                        board1.movePlayer(pionJoueur2, posJ2, false);
                    }
                } else if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_DOWN) {
                    if (viesJ1 > 0) {
                        viesJ1--;
                        player1Comp.setNbHeart(viesJ1);
                    }
                } else if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_UP) {
                    if (viesJ2 > 0) {
                        viesJ2--;
                        player2Comp.setNbHeart(viesJ2);
                    }
                }
            }
        });
        
        this.setFocusable(true);
        this.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void initCustomComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Test Global du Jeu Pirate");
        
        board1 = new project.boundary.Board();
        player1Comp = new project.boundary.PlayerComponent();
        player2Comp = new project.boundary.PlayerComponent();
        deComp = new project.boundary.DéComponent();
        
        deComp.setPreferredSize(new java.awt.Dimension(100, 100));
        
        btnLancerDe = new JButton("Lancer / Stop Dé");
        btnLancerDe.setFocusable(false);
        btnLancerDe.addActionListener(e -> {
            if (!isRolling) {
                deComp.lancerDe();
                isRolling = true;
            } else {
                deComp.timer.stop();
                isRolling = false;
            }
        });

        
        JPanel dicePanel = new JPanel(new BorderLayout());
        dicePanel.add(deComp, BorderLayout.CENTER);
        dicePanel.add(btnLancerDe, BorderLayout.SOUTH);
        
        JPanel headerPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 40, 10));
        headerPanel.add(player1Comp);
        headerPanel.add(dicePanel);
        headerPanel.add(player2Comp);
        
        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(headerPanel, BorderLayout.NORTH);
        getContentPane().add(board1, BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new testGame().setVisible(true));
    }
    
   
    private project.boundary.Board board1;
    private project.boundary.PlayerComponent player1Comp;
    private project.boundary.PlayerComponent player2Comp;
    private project.boundary.DéComponent deComp;
    private javax.swing.JButton btnLancerDe;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
