/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project.boundary;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JComponent;

/**
 *
 * @author alban
 */
public class testBoard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(testBoard.class.getName());
    
    private Pawn pionJoueur1;
    private Pawn pionJoueur2;
    private int posJ1 = 0;
    private int posJ2 = 0;

    /**
     * Creates new form testBoard
     */
    public testBoard() {
        initComponents();
        
        lancerTestComplet();
    }
    
    private void lancerTestComplet() {
        List<JComponent> casesVisuelles = new ArrayList<>();
        
        for (int i = 0; i < 30; i++) {
            casesVisuelles.add(new CaseComponent());
        }
        
        board1.initBoard(casesVisuelles);
        
        Pawn pionJoueur1 = new Pawn();
        pionJoueur1.setSize(50, 50);
        pionJoueur1.setImagePath("/images/bob.png");
        
        Pawn pionJoueur2 = new Pawn();
        pionJoueur2.setSize(50, 50); 

        board1.movePlayer(pionJoueur1, 0, true);
        board1.movePlayer(pionJoueur2, 0, false);
        pionJoueur2.setImagePath("/images/plankton.png");
        
        
        this.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_LEFT) {
                    if (posJ1 < 29) {
                        posJ1++;
                        board1.movePlayer(pionJoueur1, posJ1, true);
                    }
                } else if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_RIGHT) {
                    if (posJ2 < 29) {
                        posJ2++;
                        board1.movePlayer(pionJoueur2, posJ2, false);
                    }
                }
            }
        });
        this.setFocusable(true);
        this.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        board1 = new project.boundary.Board();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(board1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(board1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new testBoard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private project.boundary.Board board1;
    // End of variables declaration//GEN-END:variables
}
