/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package projet_pirate.playercomponent;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author lucas
 */
public class Heart extends javax.swing.JPanel {
    private boolean liveHeart = false;

    /**
     * Creates new form Heart
     */
    public Heart() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private void drawPixel(Graphics2D g2d, Color color, int startX, int col, int pixelWidth, int pixelHeight, int startY, int row) {
        g2d.setColor(color);
        g2d.fillRect(
                startX + col * pixelWidth,
                startY + row * pixelHeight,
                pixelWidth,
                pixelHeight
        );
    }
    
    public void setLiveHeart(boolean liveHeart) {
        this.liveHeart = liveHeart;
        repaint();
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
        Graphics2D g2d = (Graphics2D)g;
        
        
        // Size of each "pixel" block
        //int pixelSize = 20;
        int pixelWidth = getWidth()/7;
        int pixelHeigth = getHeight()/6;

        // Heart pattern (2 = filling pixel, 1 = black pixel, 0 = empty)
        int[][] heart = {
            {0,1,1,0,1,1,0},
            {1,2,2,1,2,2,1},
            {1,2,2,2,2,2,1},
            {0,1,2,2,2,1,0},
            {0,0,1,2,1,0,0},
            {0,0,0,1,0,0,0},
        };

        // Optional: center the heart in the panel
//        int startX = (getWidth() - heart[0].length * pixelSize) / 2;
//        int startY = (getHeight() - heart.length * pixelSize) / 2;

          int startX = 0;
          int startY = 0;

        // select fillcolor
        Color fillColor = liveHeart ? Color.RED : Color.GRAY;
        
        // Draw the heart

        for (int row = 0; row < heart.length; row++) {
            for (int col = 0; col < heart[row].length; col++) {
                switch (heart[row][col]) {
                    case 0 -> {}
                    case 1 -> drawPixel(g2d, Color.BLACK, startX, col, pixelWidth, pixelHeigth, startY, row);
                    case 2 -> drawPixel(g2d, fillColor, startX, col, pixelWidth, pixelHeigth, startY, row);
                    default -> System.err.println("projet_pirate.playercomponent.Heart.paintComponent() : invalid draw");
                   }
                
            }
        }
    }
}
